### ISSUE TITLE
Change in the return in /categories endpoint of the public-apis API

### ISSUE THREAD

**Issue by matheusfelipeog** [hyamero/collective-api#1]
Hi, I'm the maintainer of the public-apis project.

We recently made a change in the return of the `/categories` endpoint of our API to add a count key that contains the number of categories currently available in the project. This change caused unwanted behavior in collective api website when we tried to explore categories. I recommend that you update [this function](https://github.com/hyamero/collective-api/blob/main/src/App.tsx#L55) to make it fit and work properly.

Thanks for keeping this project <3

You can see more about the change at: https://github.com/davemachado/public-api/issues/29

**Comment by hyamero** [comment]
Hey, @matheusfelipeog thanks for the heads up! It's now working properly. Updated [here](https://github.com/hyamero/collective-api/blob/8297dd1ca4bc7b6b8417e89d6bdb05da9d2a191d/src/App.tsx#L79).

~[Collective APIs](https://collective-api.vercel.app/)

**Comment by matheusfelipeog** [comment]
A big thanks for the update ❤️
