### ISSUE TITLE
Regarding the current situation of the Public APIs project 

### ISSUE THREAD

**Issue by pawelborkar** [hyamero/collective-api#2]
Hi @hyamero,
Hope your doing good. This issue is regarding the current situation which we the collaborators at [Public APIs](https://github.com/public-apis/public-apis/issues/3104) are facing  regarding the future of public apis and the open source community in general.

As we've added your website in one of the unofficial list of websites in the readme, there's a possibility of a number of people visiting it. So it's one of the reasons I'm writing this issue. In order to bring this issue in front of the community members  

Please read [this](https://github.com/public-apis/public-apis/issues/3104) issue and we would encourage you to spread it on your website's homepage or write blogs or a tweet about it in order to bring this serious issue into the limelight of the community members. And help the project to survive.

Thanks, 
Pawel

**Comment by hyamero** [comment]
Hey @pawelborkar,
Sorry for the late reply. I have added a [button](https://github.com/hyamero/collective-api/blob/8af9053ffed6fd6e50af1045ffb1e679bb3b602e/src/components/Navbar.tsx#L90) that links to the archive of the said current situation below the navbar. 

![public apis situation](https://user-images.githubusercontent.com/78056869/159014878-91530b9e-a2cd-41fd-b18f-8c1b6dd7cb13.png)

**Comment by hyamero** [comment]
Furthermore, if your situation (maintainers of [Public APIs](https://github.com/public-apis/public-apis)) have settled down & have resolved the current situation, please do let me know as I am planning to improve [Collective APIs](https://collective-api.vercel.app/) with much better technologies and code. Otherwise, I won't do so. Thanks!

**Comment by pawelborkar** [comment]
Thanks for the support @hyamero,





> Furthermore, if your situation (maintainers of [Public APIs](https://github.com/public-apis/public-apis)) have settled down & have resolved the current situation, please do let me know as I am planning to improve [Collective APIs](https://collective-api.vercel.app/) with much better technologies and code. Otherwise, I won't do so. Thanks!

Sure. Will let you know if the situation gets resolved.
